package com.familytree.model;

import org.apache.log4j.Logger;

import java.time.LocalDate;
import java.time.Period;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIgnore;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.familytree.alexa.PhrasesAndConstants;

@DynamoDBTable(tableName = "PLACEHOLDER_PERSON_TABLE_NAME")
public class Person {
    private String userId;
    private String personId;
    private String firstName;
    private String lastName;
    private String phoneNumber;
    private String work;
    @DynamoDBIgnore
    private String[] hobbies;
    private String birthDate;
    private String relationToUser;

    @DynamoDBHashKey(attributeName = "personId")
    @DynamoDBAutoGeneratedKey
    public String getPersonId() {
        return this.personId;
    }

    public void setPersonId(String personId) {
        this.personId = personId;
    }

    @DynamoDBRangeKey(attributeName = "userId")
    public String getUserId() {
        return this.userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    @DynamoDBAttribute(attributeName = "firstName")
    public String getFirstName() {
        return this.firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    @DynamoDBAttribute(attributeName = "lastName")
    public String getLastName() {
        return this.lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    @DynamoDBAttribute(attributeName = "phoneNumber")
    public String getPhoneNumber() {
        return this.phoneNumber;
    }

    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    @DynamoDBAttribute(attributeName = "work")
    public String getWork() {
        return this.work;
    }

    public void setWork(String work) {
        this.work = work;
    }

    @DynamoDBAttribute(attributeName = "birthDate")
    public String getBirthDate() {
        return this.birthDate;
    }

    public void setBirthDate(String birthDate) {
        this.birthDate = birthDate;
    }

    @DynamoDBAttribute(attributeName = "relationToUser")
    public String getRelationToUser() {
        return this.relationToUser;
    }

    public void setRelationToUser(String relation) {
        this.relationToUser = relation;
    }

    public String toString() {
        return "Person(" + personId + "):" + "userId:" + userId;
    }

    @DynamoDBIgnore
    public String[] getHobbies() {
        return hobbies;
    }

    public void setHobbies(String[] hobbies) {
        this.hobbies = hobbies;
    }

    // calculates with the format 'YYYY-MM-DD' (filled with zeros '2018-01-05')
    public String calculateAge() {
        String[] data = this.birthDate.split("-");
        LocalDate birthDate = LocalDate.of(Integer.parseInt(data[0]), Integer.parseInt(data[1]),
                Integer.parseInt(data[2]));
        LocalDate now = LocalDate.now();
        return Integer.toString(Period.between(birthDate, now).getYears());
    }
}