Resources:
  PersonTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.personTableName}
      AttributeDefinitions:
        - AttributeName: personId
          AttributeType: S
        - AttributeName: userId
          AttributeType: S
      KeySchema:
        - AttributeName: personId
          KeyType: HASH
        - AttributeName: userId
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
